sudo: required
services:
  - docker

before_install:
  - docker build -t syirasky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true syirasky/react-test npm test

after_success:
  - docker build -t syirasky/multi-client ./client
  - docker build -t syirasky/multi-nginx ./nginx
  - docker build -t syirasky/multi-server  ./server
  - docker build -t syirasky/multi-worker ./worker